### ISSUE TITLE
No mapping allowed

### ISSUE THREAD

**Issue by Gavergracht** [chaptergy/lightalarm-card#15]
I am just starting with yaml, so I make a lot of mistakes. I copied your script but I get " no mapping allowed". somewhere around the datatemplate it goes wrong :( Can you help me out ?

```yml
   alias: Trigger the lightalarm
    fields:
      duration:
        description: Number of minutes for the light alarm transition period
        example: 20
    sequence:
      - service: light.turn_on
          data_template:
            entity_id: light.bedside_lamp
            rgb_color:
              - 255
              - 91
              - 36
            brightness: 255
            transition: "{{ duration | float | multiply(60) }}"
      - event: lightalarm_triggered
      - condition: state
        entity_id: input_select.lightalarm_mode
        state: Once Only
      - service: input_select.select_option
        data:
          option: 'Off'
        entity_id: input_select.lightalarm_mode
    mode: single
```

**Comment by chaptergy** [comment]
This is most likely due to the indentation being incorrect. The start of the text of `service` and `data_template` need to be aligned like this:

```yml
[...]
sequence:
  - service: light.turn_on
    data_template:
      entity_id: light.bedside_lamp
      [...]
```
